# Generated by Django 2.2.6 on 2019-11-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PR', 'PROCESSING'), ('MF', 'MATCH_FOUND'), ('NM', 'NO_MATCH'), ('FL', 'FAILED')], default='PR', max_length=30)),
                ('search_string', models.TextField(blank=True)),
                ('searches_issued', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_best_match', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('match_found', models.BooleanField(default=False)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=30)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Search')),
            ],
        ),
    ]
