# Generated by Django 2.2.6 on 2019-11-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191104_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_filepath', models.CharField(max_length=500)),
                ('query', models.TextField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Search')),
            ],
        ),
    ]
